### ISSUE TITLE
AttributeError: 'SeqReader' object has no attribute 'basic_scores'

### ISSUE THREAD

**Issue by nlpjoe** [JiayuLi-997/IntEL-SIGIR2023#1]
hello JiayuLi, we run the script but get the error:

Traceback (most recent call last):                                                                                                                                                                                 
  File "main.py", line 160, in <module>
    main()
  File "main.py", line 94, in main
    data_dict[phase].prepare()
  File "/Users/joe/codes/intel_ltr_raw/IntEL/src/models/BaseModel.py", line 110, in prepare
    self.buffer_dict[i] = self._get_feed_dict(i)
  File "/Users/joe/codes/intel_ltr_raw/IntEL/src/models/IntEL/IntEL.py", line 207, in _get_feed_dict
    feed_dict = super()._get_feed_dict(index)
  File "/Users/joe/codes/intel_ltr_raw/IntEL/src/models/GeneralSeq.py", line 36, in _get_feed_dict
    feed_dict = super()._get_feed_dict(index)
  File "/Users/joe/codes/intel_ltr_raw/IntEL/src/models/BaseModel.py", line 189, in _get_feed_dict
    feed_dict = super()._get_feed_dict(index)
  File "/Users/joe/codes/intel_ltr_raw/IntEL/src/models/BaseModel.py", line 166, in _get_feed_dict
    for i,key in enumerate(['i_id_s']+self.corpus.basic_scores): # sequence of item and base scores
AttributeError: 'SeqReader' object has no attribute 'basic_scores'

Can u give me some advice to run it correctly?

**Comment by JiayuLi-997** [comment]
Thanks for your comments. We checked the data and found that the provided .pkl file had something wrong.
We have deleted these .pkl file from the repository so that they will be regenerated the next time you run the script (you can also regenerate it by adding '--regenerate 1' in the command).
Also we made some small modifiations to BaseModel.py. Please kindly update it.
